### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jeremyworger** [carthach/rhythmCAT#1]
Hey there, was curious to know if RhythmCAT is still in development, and if there will be a release as per the description?  
Was also wondering if there would ever be a windows vst in the future.

Cheers,

Jeremy

**Comment by carthach** [comment]
Hey Jeremy,

Thanks for your interest! I have grand plans for a full redesign of RhythmCAT, but I no longer work on it as my day job so it's impossible to say when, sorry! When I do get back to it, Windows support is definitely on the cards.

**Comment by jeremyworger** [comment]
Sounds good. Grand plans sound very intriguing !
Would it work on OS9 (on windows?)

**Comment by jeremydeanw** [comment]
Just out of curiosity, the VST demo is for OSX, is this correct?  Just wondering if I can run it in something like: http://www.columbia.edu/~em36/macos9win.html

**Comment by carthach** [comment]
OS X only, Mac OS 9 is ancient so not sure that would work...

C

**Comment by tvmcc** [comment]
I realize this is old, and you may have lost complete interest in this project, but any idea if the old source works in Logic Pro X? Can't seem to get it to open, and would love to make use of your concept.

**Comment by carthach** [comment]
Try this one,

https://drive.google.com/file/d/1mXQnA0ngGQ-IZPqH-lLxMijvavnZ1d50/view?usp=sharing

Please don't share with anyone as it's a full copy!

**Comment by jeremydeanw** [comment]
!!! Ok, I will try this out today. I won't share it with anyone.
I'll get back to you in a bit.

J

**Comment by tvmcc** [comment]
Hey there,

Unfortunately it doesn't open in Ableton or Logic Pro X for me:


Thanks so much for trying, will give it a try on my laptop, and get back to
you.

Titus

**Comment by carthach** [comment]
You may need to remove the quarantine attributes on the file (command
below). What OS version are you using?

sudo xattr -r -d com.apple.quarantine <Plugin File>

**Comment by carthach** [comment]
You may need to remove the quarantine attributes on the file. What OS version are you on?

sudo xattr -r -d com.apple.quarantine <Plugin File>

**Comment by tvmcc** [comment]
Hey there,

Thanks so much for the info, and the question.

I'm currently running 10.15.2, and logic 10.4.8

I am having issues understanding what name i should use for program file
when using quarantine?

sudo xattr -r -d com.apple.quarantine rhythmCAT.component


Be a great day,

Titus
